# Node.js 20버전 이미지 사용
FROM node:20

# 작업 디렉토리 설정
WORKDIR /source

# package.json과 package-lock.json 파일을 컨테이너로 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 소스 코드 복사
COPY . .

# 봇 실행
CMD ["node", "src/index.js"]

# 포트 열기 (필요시)
EXPOSE 3000